"""constraints included

Revision ID: 864a7feaaacd
Revises: e3f15fb2cfe3
Create Date: 2025-09-16 09:41:39.159204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864a7feaaacd'
down_revision = 'e3f15fb2cfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
